/*
 * This Java source file was generated by the Gradle 'init' task.
 */
    package basiclibrary;

import org.checkerframework.checker.units.qual.min;

import javax.swing.*;
import java.lang.reflect.Array;
import java.util.*;

public class Library<myans, max> {

    public static void main(String[] args) {
        int[] myRoll = roll(6);
        for (int i = 0; i < myRoll.length; i++) {
            System.out.println(myRoll[i]);
        }

    }

    public static int[] roll(int valueOfRoll) {
        int[] returnNewArray = new int[valueOfRoll];
        for (int i = 0; i < returnNewArray.length; i++) {
            returnNewArray[i] = (int) (Math.random() * 6 + 1);
        }
        return returnNewArray;


    }

    public static boolean containsDuplicates(int[] numElementsInx) {
        for (int i = 0; i < numElementsInx.length; i++) {
            for (int j = 1; j < numElementsInx.length; j++) {
                if (numElementsInx[i] == numElementsInx[j] && i != j) return true;
            }
        }
        return false;
    }

    public static int calculateAvg(int[] cal){
        int avg = 0;
        for(int i = 0; i < cal.length; i++){
            avg = avg + cal[i];
        }
        return avg/cal.length;
    }

    public static String arrayAvgValue(int[][] lowestArray){
        ArrayList<Integer> averages = new ArrayList<>();
        int lowestAvg = Integer.MAX_VALUE;
        int lowestAvgIndex = 0;
        int avg = 0;
        for(int i = 0; i < lowestArray.length; i++){
            int sum = 0;
            for(int j = 0; j < lowestArray[i].length; j++){
                sum += lowestArray[i][j];
                avg = sum/7;
            }
            averages.add(avg);
        }

        for(int j = 0; j < averages.size(); j++){
            if(averages.get(j) < lowestAvg){
                lowestAvg = averages.get(j);
                lowestAvgIndex = j;
            }
        }
        return Arrays.toString(lowestArray[lowestAvgIndex]);
    }



        public static String valueMinMax (int[][] myData) {
            String myans = "";
            int min = myData[0][0];
            int max = myData[0][0];
            HashSet<Integer> set = new HashSet<>();
            for (int i = 0; i < myData.length; i++) {
                for (int j = 0; j < myData[i].length; j++) {
                    if ((myData[i][j]) < min) {
                        min = myData[i][j];
                    }
                    if ((myData[i][j]) > max) {
                        max = myData[i][j];
                        set.add(myData[i][j]);
                    }
                }
            }
            for (int i = min; i <= max; i++) {
                if (!set.contains(i)) {
                    myans += " Never saw temperature: " + i;
                }
            }
            return myans;
        }







}








